/**
 * Drone archetypes. Distances are relative to the player; the run axis is +X.
 */
export const DRONE_TYPES = {
  scout: {
    id: "scout",
    hp: 3,
    scale: 1.9,
    radius: 1.45,
    glow: 0xff2d55,
    score: 100,
    ahead: [13, 22],
    height: [2.2, 5.5],
    lateral: 7,
    strafeSpeed: 1.3,
    fireInterval: [1.6, 2.6],
    burst: 1,
    burstGap: 0,
    chargeTime: 0.6,
    boltSpeed: 17,
    boltDamage: 14,
    lifetime: 22,
    unlockDistance: 0,
  },
  gunship: {
    id: "gunship",
    hp: 9,
    scale: 2.4,
    radius: 2.1,
    glow: 0xffa21f,
    score: 300,
    ahead: [20, 28],
    height: [5, 8],
    lateral: 4,
    strafeSpeed: 0.6,
    fireInterval: [2.6, 3.4],
    burst: 3,
    burstGap: 0.14,
    chargeTime: 0.9,
    boltSpeed: 19,
    boltDamage: 12,
    lifetime: 30,
    unlockDistance: 450,
  },
  kamikaze: {
    id: "kamikaze",
    hp: 2,
    scale: 1.8,
    radius: 1.55,
    glow: 0xff6a00,
    score: 150,
    ahead: [17, 24],
    height: [3, 6],
    lateral: 5,
    strafeSpeed: 2.2,
    fireInterval: [1.2, 1.8],
    burst: 0,
    burstGap: 0,
    chargeTime: 0.9,
    boltSpeed: 0,
    boltDamage: 34,
    diveSpeed: 17,
    lifetime: 14,
    unlockDistance: 250,
  },
};
