/**
 * Drone archetypes. Distances are relative to the player; the run axis is +X.
 */
export const DRONE_TYPES = {
  scout: {
    id: "scout",
    hp: 6,
    scale: 1.9,
    radius: 1.45,
    glow: 0xff2d55,
    score: 100,
    ahead: [11, 19],
    height: [2.2, 5.5],
    lateral: 7,
    strafeSpeed: 1.3,
    fireInterval: [0.9, 1.5],
    burst: 2,
    burstGap: 0.16,
    chargeTime: 0.6,
    boltSpeed: 20,
    boltDamage: 14,
    lifetime: 32,
    unlockDistance: 0,
  },
  gunship: {
    id: "gunship",
    hp: 18,
    scale: 2.4,
    radius: 2.1,
    glow: 0xffa21f,
    score: 300,
    ahead: [17, 25],
    height: [5, 8],
    lateral: 4,
    strafeSpeed: 0.6,
    fireInterval: [1.6, 2.2],
    burst: 4,
    burstGap: 0.14,
    chargeTime: 0.9,
    boltSpeed: 22,
    boltDamage: 12,
    lifetime: 40,
    unlockDistance: 300,
  },
  kamikaze: {
    id: "kamikaze",
    hp: 4,
    scale: 1.8,
    radius: 1.55,
    glow: 0xff6a00,
    score: 150,
    ahead: [17, 24],
    height: [3, 6],
    lateral: 5,
    strafeSpeed: 2.2,
    fireInterval: [0.7, 1.1],
    burst: 0,
    burstGap: 0,
    chargeTime: 0.9,
    boltSpeed: 0,
    boltDamage: 34,
    diveSpeed: 21,
    lifetime: 14,
    unlockDistance: 120,
  },
};
