/**
 * VX-series loadout. Switch with 1–4 / Q / mouse wheel (touch: HUD chips).
 * Damage is per hit (scout 3 HP, gunship 9, kamikaze 2).
 */
export const WEAPONS = [
  {
    id: "carbine",
    code: "VX-06",
    name: "CARBINE",
    fireRate: 11,
    overclockRate: 19,
    magSize: 32,
    reloadTime: 1.25,
    damage: 1,
    baseSpread: 0.003,
    spreadPerShot: 0.0028,
    maxSpread: 0.028,
    recoil: 1,
    tracer: 0x5dff3a,
    sound: { volume: 0.32, detune: 0 },
  },
  {
    id: "smg",
    code: "VX-09",
    name: "SMG",
    fireRate: 16,
    overclockRate: 26,
    magSize: 45,
    reloadTime: 1.1,
    damage: 0.65,
    baseSpread: 0.006,
    spreadPerShot: 0.0032,
    maxSpread: 0.04,
    recoil: 0.6,
    tracer: 0x9bff7a,
    sound: { volume: 0.26, detune: 350 },
  },
  {
    id: "rail",
    code: "VX-12",
    name: "RAIL",
    fireRate: 1.8,
    overclockRate: 3.5,
    magSize: 6,
    reloadTime: 1.6,
    damage: 5,
    baseSpread: 0.0004,
    spreadPerShot: 0.004,
    maxSpread: 0.01,
    recoil: 3,
    tracer: 0xd9ff3b,
    sound: { volume: 0.5, detune: -700 },
  },
  {
    id: "heavy",
    code: "VX-14",
    name: "HEAVY",
    fireRate: 8,
    overclockRate: 13,
    magSize: 90,
    reloadTime: 2.6,
    damage: 1.5,
    baseSpread: 0.005,
    spreadPerShot: 0.0024,
    maxSpread: 0.032,
    recoil: 1.6,
    tracer: 0x5dff3a,
    sound: { volume: 0.4, detune: -300 },
  },
];
